version: '3.8'

services:
  analytics:
    build: .
    container_name: analytics_pi
    restart: always
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER=dashboard_pi_mqtt
      - MQTT_PORT=1883
    volumes:
      - ./analytics_pi:/app
    command: ["python", "analytics_main.py"]

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    restart: always
    network_mode: "host"
